/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DiscoveryOrganizationIdProjectIdRouteImport } from './routes/discovery/$organizationId.$projectId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DiscoveryOrganizationIdProjectIdRoute =
  DiscoveryOrganizationIdProjectIdRouteImport.update({
    id: '/discovery/$organizationId/$projectId',
    path: '/discovery/$organizationId/$projectId',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/discovery/$organizationId/$projectId': typeof DiscoveryOrganizationIdProjectIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/discovery/$organizationId/$projectId': typeof DiscoveryOrganizationIdProjectIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/discovery/$organizationId/$projectId': typeof DiscoveryOrganizationIdProjectIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/discovery/$organizationId/$projectId'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/discovery/$organizationId/$projectId'
  id: '__root__' | '/' | '/discovery/$organizationId/$projectId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DiscoveryOrganizationIdProjectIdRoute: typeof DiscoveryOrganizationIdProjectIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/discovery/$organizationId/$projectId': {
      id: '/discovery/$organizationId/$projectId'
      path: '/discovery/$organizationId/$projectId'
      fullPath: '/discovery/$organizationId/$projectId'
      preLoaderRoute: typeof DiscoveryOrganizationIdProjectIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DiscoveryOrganizationIdProjectIdRoute: DiscoveryOrganizationIdProjectIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
